name: TideReputation
author: xdproston
version: 1.3
api-version: 1.19
libraries:
  - net.kyori:adventure-text-minimessage:4.14.0
  - org.xerial:sqlite-jdbc:3.8.11.2
  - com.zaxxer:HikariCP:5.1.0
  - mysql:mysql-connector-java:8.0.33
  - com.j256.ormlite:ormlite-jdbc:6.1
depend: [PlaceholderAPI]
main: net.xdproston.tiderep.Main
commands:
  reputation:
    aliases: [rep]
    description: Main reputation command of TideReputation.
    permission: tiderep.cmd.reputation
  adminreputation:
    aliases: [arep, adminrep, areputation]
    description: Admin reputation command of TideReputation.
    permission: tiderep.cmd.adminreputation
  reputationreload:
    aliases: [repreload]
    description: Reload command of TideReputation.
    permission: tiderep.cmd.reputationreload
permissions:
  tiderep.cmd.reputation:
    description: Permission for cmd reputation
    default: op
  tiderep.cmd.adminreputation:
    description: Permission for cmd adminreputation
    default: op
  tiderep.cmd.reputationreload:
    description: Permission for cmd reputationreload
    default: op